import{cleanFolder,makeContactHtml,makeManifest,makeSnippet,makeVCard}from"./core.mjs";
const $=id=>document.getElementById(id), form=$("generator-form"),canvas=$("preview"),ctx=canvas.getContext("2d"),status=$("status");let sourceImage=null,lastSnippet="";
const fields=["firstName","lastName","title","organization","cell","workPhone","email","workEmail","street","postalCode","city","country","folderName"];
function values(){return Object.fromEntries(fields.map(id=>[id,$(id).value.trim()]))}
function suggestedFolder(){const v=values();return cleanFolder(`${v.lastName} ${v.firstName}`)}
function drawPlaceholder(){ctx.fillStyle="#f1eee7";ctx.fillRect(0,0,600,600);ctx.fillStyle="#003789";ctx.textAlign="center";ctx.font="26px sans-serif";ctx.fillText("Foto auswählen",300,310)}
function drawPhoto(target=ctx,white=false){if(!sourceImage){drawPlaceholder();return}target.save();target.fillStyle=white?"#fff":"#f1eee7";target.fillRect(0,0,600,600);const zoom=Number($("zoom").value)/100,scale=Math.max(600/sourceImage.naturalWidth,600/sourceImage.naturalHeight)*zoom,dw=sourceImage.naturalWidth*scale,dh=sourceImage.naturalHeight*scale,x=(600-dw)/2,y=(600-dh)*(Number($("position").value)/100);target.drawImage(sourceImage,x,y,dw,dh);target.restore()}
function updatePhoto(){drawPhoto();$("zoomValue").value=`${$("zoom").value} %`;$("positionValue").value=`${$("position").value} %`}
[$("firstName"),$("lastName")].forEach(el=>el.addEventListener("input",()=>{if(!$("folderName").dataset.edited)$("folderName").value=suggestedFolder()}));
$("folderName").addEventListener("input",()=>{$("folderName").dataset.edited="1"});
$("photo").addEventListener("change",()=>{const file=$("photo").files[0];if(!file)return;const img=new Image();img.onload=()=>{sourceImage=img;updatePhoto();URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(file)});
[$("zoom"),$("position")].forEach(el=>el.addEventListener("input",updatePhoto));
$("resetPhoto").addEventListener("click",()=>{$("zoom").value=100;$("position").value=25;updatePhoto()});
$("copySnippet").addEventListener("click",async()=>{await navigator.clipboard.writeText(lastSnippet);setStatus("Startseiten-Eintrag wurde kopiert.","success")});
function setStatus(message,type=""){status.textContent=message;status.className=`status ${type}`}
function canvasBlob(type,quality){return new Promise(resolve=>canvas.toBlob(resolve,type,quality))}
form.addEventListener("submit",async event=>{event.preventDefault();if(!form.reportValidity()||!sourceImage)return setStatus("Bitte alle Pflichtfelder und ein Foto ergänzen.","error");if(!window.JSZip)return setStatus("ZIP-Modul konnte nicht geladen werden. Bitte Internetverbindung prüfen.","error");try{setStatus("Paket wird erstellt …");const d=values();d.folderName=cleanFolder(d.folderName);$("folderName").value=d.folderName;drawPhoto(ctx,true);const jpeg=(await canvasBlob("image/jpeg",.9)),jpeg64=(await blobToDataUrl(jpeg)).split(",")[1];drawPhoto(ctx,false);const png=await canvasBlob("image/png");const zip=new JSZip(),folder=zip.folder(d.folderName);folder.file("index.html",makeContactHtml(d));folder.file("Profilbild.png",png);folder.file("Vcard.vcf",makeVCard(d,jpeg64));folder.file("manifest.json",makeManifest(d));lastSnippet=makeSnippet(d);zip.file("startseite-eintrag.html",lastSnippet);zip.file("ANLEITUNG.txt",instructions(d));const blob=await zip.generateAsync({type:"blob"});download(blob,`${d.folderName}.zip`);$("copySnippet").disabled=false;setStatus("Fertig: ZIP wurde heruntergeladen. Danach den Kontaktordner zu GitHub hochladen.","success")}catch(error){console.error(error);setStatus("Das Paket konnte nicht erstellt werden.","error")}});
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function instructions(d){return `HCI VCARD – KURZANLEITUNG\r\n\r\n1. ZIP-Datei entpacken.\r\n2. Den Ordner „${d.folderName}“ in das Hauptverzeichnis des GitHub-Repositories HCI-Vcard hochladen.\r\n3. Den Inhalt von „startseite-eintrag.html“ an der passenden Stelle in die index.html der Startseite einfügen.\r\n4. Änderungen auf GitHub speichern und kurz warten, bis GitHub Pages aktualisiert ist.\r\n\r\nKontaktadresse:\r\nhttps://officehcijuniors-arch.github.io/HCI-Vcard/${encodeURIComponent(d.folderName)}/\r\n\r\nHinweis: Das Profilfoto ist bereits in Profilbild.png und in Vcard.vcf enthalten. Android und iOS können die Kontaktseite über den Browser zum Startbildschirm hinzufügen.`}
function registerWebMCP(){const c=document.modelContext;if(!c?.registerTool)return;try{c.registerTool({name:"stage_hci_contact",title:"HCI-Kontakt vorbereiten",description:"Füllt die sichtbaren Kontaktdaten des HCI-VCard-Generators aus. Das Foto und der abschließende ZIP-Download erfolgen weiterhin durch die Person im Browser.",inputSchema:{type:"object",properties:{firstName:{type:"string"},lastName:{type:"string"},title:{type:"string"},organization:{type:"string"},cell:{type:"string"},workPhone:{type:"string"},email:{type:"string"},workEmail:{type:"string"}},required:["firstName","lastName","title"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=="object"||!["firstName","lastName","title"].every(k=>typeof input[k]==="string"&&input[k].trim()))throw new Error("Vorname, Nachname und Funktion werden benötigt.");for(const[k,v]of Object.entries(input))if($(k))$(k).value=String(v);$("folderName").value=suggestedFolder();window.scrollTo({top:0,behavior:"smooth"});return{status:"prepared",folderName:$("folderName").value}}})}catch(e){console.warn("WebMCP nicht verfügbar",e)}}
drawPlaceholder();registerWebMCP();
